/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ementor;

import javax.swing.JOptionPane;

/**
 *
 * @author Anderson
 */
public class MenuCadastrarProfessor extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuCadastrarProfessor.class.getName());

    /**
     * Creates new form Cadastros
     */
    public MenuCadastrarProfessor() {
        initComponents();
        
        this.setResizable(false); 
    
        this.setSize(800, 640); 
    
        this.setLocationRelativeTo(null);
        
        lblSalarioLiquido.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        lblNome = new javax.swing.JTextField();
        txtNome = new javax.swing.JLabel();
        lblDataNascimento = new javax.swing.JTextField();
        txtDataNascimento = new javax.swing.JLabel();
        txtCPF = new javax.swing.JLabel();
        lblCPF = new javax.swing.JTextField();
        txtTelefone = new javax.swing.JLabel();
        lblTelefone = new javax.swing.JTextField();
        txtRua = new javax.swing.JLabel();
        lblRua = new javax.swing.JTextField();
        txtBairro = new javax.swing.JLabel();
        lblBairro = new javax.swing.JTextField();
        txtCidade = new javax.swing.JLabel();
        lblCidade = new javax.swing.JTextField();
        lblEstado = new javax.swing.JTextField();
        txtEstado = new javax.swing.JLabel();
        txtDataAdmissao = new javax.swing.JLabel();
        lblDataAdmissao = new javax.swing.JTextField();
        txtSalarioBruto = new javax.swing.JLabel();
        lblSalarioBruto = new javax.swing.JTextField();
        lblSalarioLiquido = new javax.swing.JTextField();
        txtSalarioBruto1 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        txtSalarioBruto2 = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        txtSalarioBruto3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jButton4.setBackground(new java.awt.Color(45, 60, 135));
        jButton4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Cadastrar");
        jButton4.setBorderPainted(false);
        jButton4.addActionListener(this::jButton4ActionPerformed);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 400));
        setSize(new java.awt.Dimension(600, 400));

        jPanel1.setBackground(new java.awt.Color(30, 30, 30));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanel1.setLayout(null);

        jPanel5.setBackground(new java.awt.Color(222, 222, 222));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 606, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5);
        jPanel5.setBounds(794, 606, 0, 606);

        jPanel6.setBackground(new java.awt.Color(30, 30, 30));
        jPanel6.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanel6.setLayout(null);

        lblNome.addActionListener(this::lblNomeActionPerformed);
        jPanel6.add(lblNome);
        lblNome.setBounds(30, 50, 125, 22);

        txtNome.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        txtNome.setForeground(new java.awt.Color(255, 255, 255));
        txtNome.setText("Nome");
        jPanel6.add(txtNome);
        txtNome.setBounds(30, 30, 37, 16);

        lblDataNascimento.setForeground(java.awt.Color.gray);
        lblDataNascimento.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        lblDataNascimento.setText("AAAA/MM/DD");
        lblDataNascimento.setToolTipText("");
        lblDataNascimento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lblDataNascimentoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lblDataNascimentoFocusLost(evt);
            }
        });
        lblDataNascimento.addActionListener(this::lblDataNascimentoActionPerformed);
        jPanel6.add(lblDataNascimento);
        lblDataNascimento.setBounds(30, 110, 125, 22);

        txtDataNascimento.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        txtDataNascimento.setForeground(new java.awt.Color(255, 255, 255));
        txtDataNascimento.setText("Data de Nascimento");
        jPanel6.add(txtDataNascimento);
        txtDataNascimento.setBounds(30, 80, 108, 16);

        txtCPF.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        txtCPF.setForeground(new java.awt.Color(255, 255, 255));
        txtCPF.setText("CPF");
        jPanel6.add(txtCPF);
        txtCPF.setBounds(30, 140, 37, 16);

        lblCPF.addActionListener(this::lblCPFActionPerformed);
        jPanel6.add(lblCPF);
        lblCPF.setBounds(30, 160, 125, 22);

        txtTelefone.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        txtTelefone.setForeground(new java.awt.Color(255, 255, 255));
        txtTelefone.setText("Telefone");
        jPanel6.add(txtTelefone);
        txtTelefone.setBounds(30, 200, 60, 16);

        lblTelefone.addActionListener(this::lblTelefoneActionPerformed);
        jPanel6.add(lblTelefone);
        lblTelefone.setBounds(30, 220, 125, 22);

        txtRua.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        txtRua.setForeground(new java.awt.Color(255, 255, 255));
        txtRua.setText("Rua");
        jPanel6.add(txtRua);
        txtRua.setBounds(30, 250, 37, 16);

        lblRua.addActionListener(this::lblRuaActionPerformed);
        jPanel6.add(lblRua);
        lblRua.setBounds(30, 270, 125, 22);

        txtBairro.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        txtBairro.setForeground(new java.awt.Color(255, 255, 255));
        txtBairro.setText("Bairro");
        jPanel6.add(txtBairro);
        txtBairro.setBounds(30, 310, 37, 16);

        lblBairro.addActionListener(this::lblBairroActionPerformed);
        jPanel6.add(lblBairro);
        lblBairro.setBounds(30, 330, 125, 22);

        txtCidade.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        txtCidade.setForeground(new java.awt.Color(255, 255, 255));
        txtCidade.setText("Cidade");
        jPanel6.add(txtCidade);
        txtCidade.setBounds(30, 360, 60, 16);

        lblCidade.addActionListener(this::lblCidadeActionPerformed);
        jPanel6.add(lblCidade);
        lblCidade.setBounds(30, 390, 125, 22);

        lblEstado.addActionListener(this::lblEstadoActionPerformed);
        jPanel6.add(lblEstado);
        lblEstado.setBounds(30, 440, 125, 22);

        txtEstado.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        txtEstado.setForeground(new java.awt.Color(255, 255, 255));
        txtEstado.setText("Estado");
        jPanel6.add(txtEstado);
        txtEstado.setBounds(30, 420, 37, 16);

        txtDataAdmissao.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        txtDataAdmissao.setForeground(new java.awt.Color(255, 255, 255));
        txtDataAdmissao.setText("Data de Admissão");
        jPanel6.add(txtDataAdmissao);
        txtDataAdmissao.setBounds(180, 30, 100, 16);

        lblDataAdmissao.setForeground(java.awt.Color.gray);
        lblDataAdmissao.setText("AAAA/MM/DD");
        lblDataAdmissao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lblDataAdmissaoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lblDataAdmissaoFocusLost(evt);
            }
        });
        lblDataAdmissao.addActionListener(this::lblDataAdmissaoActionPerformed);
        jPanel6.add(lblDataAdmissao);
        lblDataAdmissao.setBounds(180, 50, 125, 22);

        txtSalarioBruto.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        txtSalarioBruto.setForeground(new java.awt.Color(255, 255, 255));
        txtSalarioBruto.setText("Salario Bruto");
        jPanel6.add(txtSalarioBruto);
        txtSalarioBruto.setBounds(180, 80, 80, 16);

        lblSalarioBruto.addActionListener(this::lblSalarioBrutoActionPerformed);
        jPanel6.add(lblSalarioBruto);
        lblSalarioBruto.setBounds(180, 110, 125, 22);

        lblSalarioLiquido.addActionListener(this::lblSalarioLiquidoActionPerformed);
        jPanel6.add(lblSalarioLiquido);
        lblSalarioLiquido.setBounds(180, 160, 125, 22);

        txtSalarioBruto1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        txtSalarioBruto1.setForeground(new java.awt.Color(255, 255, 255));
        txtSalarioBruto1.setText("Chefia");
        jPanel6.add(txtSalarioBruto1);
        txtSalarioBruto1.setBounds(180, 200, 90, 16);

        buttonGroup1.add(jCheckBox1);
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Não");
        jPanel6.add(jCheckBox1);
        jCheckBox1.setBounds(180, 250, 84, 20);

        txtSalarioBruto2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        txtSalarioBruto2.setForeground(new java.awt.Color(255, 255, 255));
        txtSalarioBruto2.setText("Salario Líquido");
        jPanel6.add(txtSalarioBruto2);
        txtSalarioBruto2.setBounds(180, 140, 90, 16);

        buttonGroup1.add(jCheckBox2);
        jCheckBox2.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox2.setText("Sim");
        jCheckBox2.addActionListener(this::jCheckBox2ActionPerformed);
        jPanel6.add(jCheckBox2);
        jCheckBox2.setBounds(180, 220, 84, 20);

        buttonGroup2.add(jCheckBox3);
        jCheckBox3.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox3.setText("Não");
        jPanel6.add(jCheckBox3);
        jCheckBox3.setBounds(180, 340, 84, 20);

        buttonGroup2.add(jCheckBox4);
        jCheckBox4.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox4.setText("Sim");
        jPanel6.add(jCheckBox4);
        jCheckBox4.setBounds(180, 310, 84, 20);

        txtSalarioBruto3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        txtSalarioBruto3.setForeground(new java.awt.Color(255, 255, 255));
        txtSalarioBruto3.setText("Coordenação");
        jPanel6.add(txtSalarioBruto3);
        txtSalarioBruto3.setBounds(180, 290, 90, 16);

        jTabbedPane2.addTab("Dados Pessoais", jPanel6);

        jPanel1.add(jTabbedPane2);
        jTabbedPane2.setBounds(0, 30, 800, 510);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("eMentor Plus - Professor");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 10, 800, 16);

        jButton1.setBackground(new java.awt.Color(45, 60, 135));
        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Voltar");
        jButton1.setBorderPainted(false);
        jButton1.setMaximumSize(new java.awt.Dimension(100, 22));
        jButton1.setMinimumSize(new java.awt.Dimension(100, 22));
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jPanel1.add(jButton1);
        jButton1.setBounds(550, 550, 100, 25);

        jButton2.setBackground(new java.awt.Color(45, 60, 135));
        jButton2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Cadastrar");
        jButton2.setBorderPainted(false);
        jButton2.setMaximumSize(new java.awt.Dimension(100, 22));
        jButton2.setMinimumSize(new java.awt.Dimension(100, 22));
        jButton2.addActionListener(this::jButton2ActionPerformed);
        jPanel1.add(jButton2);
        jButton2.setBounds(670, 550, 100, 25);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void lblSalarioBrutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblSalarioBrutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblSalarioBrutoActionPerformed

    private void lblDataAdmissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblDataAdmissaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblDataAdmissaoActionPerformed

    private void lblEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblEstadoActionPerformed

    private void lblCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCidadeActionPerformed

    private void lblBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblBairroActionPerformed

    private void lblRuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblRuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblRuaActionPerformed

    private void lblTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTelefoneActionPerformed

    private void lblCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCPFActionPerformed

    private void lblDataNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblDataNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblDataNascimentoActionPerformed

    private void lblNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblNomeActionPerformed

    private void lblSalarioLiquidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblSalarioLiquidoActionPerformed
        
    }//GEN-LAST:event_lblSalarioLiquidoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        MenuOpçõesProfessor MinhaJanela = new MenuOpçõesProfessor();
        MinhaJanela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        if (lblNome.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Preencha o nome.", "Campo obrigatório", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (lblDataNascimento.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Preencha a data de nascimento.", "Campo obrigatório", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (lblCPF.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Preencha o CPF.", "Campo obrigatório", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (lblTelefone.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Preencha o telefone.", "Campo obrigatório", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (lblRua.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Preencha a rua.", "Campo obrigatório", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (lblBairro.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Preencha o bairro.", "Campo obrigatório", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (lblCidade.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Preencha a cidade.", "Campo obrigatório", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (lblEstado.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Preencha o estado.", "Campo obrigatório", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (lblDataAdmissao.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Preencha a data de admissão.", "Campo obrigatório", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (lblSalarioBruto.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Preencha o salário bruto.", "Campo obrigatório", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (!jCheckBox1.isSelected() && !jCheckBox2.isSelected()) {
            JOptionPane.showMessageDialog(this, "Selecione se é Chefia (Sim/Não).", "Campo obrigatório", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (!jCheckBox3.isSelected() && !jCheckBox4.isSelected()) {
            JOptionPane.showMessageDialog(this, "Selecione se é Coordenação (Sim/Não).", "Campo obrigatório", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            long cpf = Long.parseLong(lblCPF.getText());
            double salarioBruto = Double.parseDouble(lblSalarioBruto.getText());

            if (salarioBruto < 0) {
                JOptionPane.showMessageDialog(this, "O salário bruto não pode ser negativo.", "Valor inválido", JOptionPane.WARNING_MESSAGE);
                return;
            }

            boolean isChefia = jCheckBox2.isSelected();       // "Sim"
            boolean isCoordenacao = jCheckBox4.isSelected();  // "Sim"

            Professor professor = new Professor();
            professor.SetDados(
                lblNome.getText(),
                lblDataNascimento.getText(),
                cpf,
                lblTelefone.getText(),
                lblRua.getText(),
                lblBairro.getText(),
                lblCidade.getText(),
                lblEstado.getText(),
                lblDataAdmissao.getText(),
                salarioBruto,
                isChefia,
                isCoordenacao
            );

            ConexoesMySQL banco = new ConexoesMySQL();
            banco.insereProfessor(professor);

            lblSalarioLiquido.setText(String.format("%.2f", professor.calcularSalarioLiquido()));

            MenuOpçõesProfessor menu = new MenuOpçõesProfessor();
            menu.setVisible(true);
            this.dispose();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                "Verifique se CPF e salário bruto foram preenchidos com números válidos.",
                "Erro de formato", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void lblDataNascimentoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblDataNascimentoFocusGained

        if (lblDataNascimento.getText().equals("AAAA/MM/DD")) {
            lblDataNascimento.setText("");
            lblDataNascimento.setForeground(java.awt.Color.BLACK);
        }
    }//GEN-LAST:event_lblDataNascimentoFocusGained

    private void lblDataNascimentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblDataNascimentoFocusLost

            if (lblDataNascimento.getText().trim().isEmpty()) {
                lblDataNascimento.setText("AAAA/MM/DD");
                lblDataNascimento.setForeground(java.awt.Color.GRAY);
        }
    }//GEN-LAST:event_lblDataNascimentoFocusLost

    private void lblDataAdmissaoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblDataAdmissaoFocusGained
         if (lblDataAdmissao.getText().equals("AAAA/MM/DD")) {
            lblDataAdmissao.setText("");
            lblDataAdmissao.setForeground(java.awt.Color.BLACK);
        }
    }//GEN-LAST:event_lblDataAdmissaoFocusGained

    private void lblDataAdmissaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblDataAdmissaoFocusLost
         if (lblDataAdmissao.getText().trim().isEmpty()) {
                lblDataAdmissao.setText("AAAA/MM/DD");
                lblDataAdmissao.setForeground(java.awt.Color.GRAY);
        }
    }//GEN-LAST:event_lblDataAdmissaoFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuCadastrarProfessor().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField lblBairro;
    private javax.swing.JTextField lblCPF;
    private javax.swing.JTextField lblCidade;
    private javax.swing.JTextField lblDataAdmissao;
    private javax.swing.JTextField lblDataNascimento;
    private javax.swing.JTextField lblEstado;
    private javax.swing.JTextField lblNome;
    private javax.swing.JTextField lblRua;
    private javax.swing.JTextField lblSalarioBruto;
    private javax.swing.JTextField lblSalarioLiquido;
    private javax.swing.JTextField lblTelefone;
    private javax.swing.JLabel txtBairro;
    private javax.swing.JLabel txtCPF;
    private javax.swing.JLabel txtCidade;
    private javax.swing.JLabel txtDataAdmissao;
    private javax.swing.JLabel txtDataNascimento;
    private javax.swing.JLabel txtEstado;
    private javax.swing.JLabel txtNome;
    private javax.swing.JLabel txtRua;
    private javax.swing.JLabel txtSalarioBruto;
    private javax.swing.JLabel txtSalarioBruto1;
    private javax.swing.JLabel txtSalarioBruto2;
    private javax.swing.JLabel txtSalarioBruto3;
    private javax.swing.JLabel txtTelefone;
    // End of variables declaration//GEN-END:variables
}
